using System.Collections.Generic;

namespace QuotesAlexaSkill.Models
{
    class QuoteModel
    {
        public int Id { get; set; }
        public string Quote { get; set; }


        public QuoteModel(int id, string quote)
        {
            Id = id;
            Quote = quote;
        }

        public static List<QuoteModel> QuotesArray()
        {
            List<QuoteModel> theQuotes = new List<QuoteModel>
            {
                new QuoteModel(0, "¡Berta la que mas liao!"),
                new QuoteModel(1, "¡Mariscos Recio!, ¡el mar al mejor precio!"),
                new QuoteModel(2, "¡Atrás, panchito!"),
                new QuoteModel(3, "¡Hala! ¡A ver si va a costar un niño más que un coche!"),
                new QuoteModel(4, "Mariscos Recio patrocina esta defunción."),
                new QuoteModel(5, "En esta comunidad, ¡yo soy la ley!"),
                new QuoteModel(6, "Berta... Y mi Cola Cao?"),
                new QuoteModel(7, "Tres juntas de suspensión por tráfico de rebozados."),
                new QuoteModel(8, "¡Melón, cumple con tu misión!"),
                new QuoteModel(9, "Te pongo una multa, ¿quieres soplar de mi alcoholímetro?"),
                new QuoteModel(10, "Antonio Recio, mayorista. ¡No limpio pescado!"),
                new QuoteModel(11, "Antonio Recio, mayorist, I don't clean fish."),
                new QuoteModel(12, "Mariscos Recio, por cada kilo de langostinos una nécora de regalo, fresquísimos, te bailan flamenco."),
                new QuoteModel(13, "In nomine Patri et Fili et Spiriti Santi, amén"),
                new QuoteModel(14, "Enrique, estás muy negativo ¡Me minas la moral!"),
                new QuoteModel(15, "¡A mí no me cae bien nadie! Bueno, el papa y Rafa Nadal."),
                new QuoteModel(16, "¡La hoja de reclamaciones! ¡Que venga el encargado!"),
                new QuoteModel(17, "Berta y yo jugamos a cosas, hacemos el guardia civil, la niña del exorcista, Heidi y el abuelito..."),
                new QuoteModel(18, "¿Qué hacéis? ¿Conspirando contra mí?"),
                new QuoteModel(19, "¡No me toques la cabeza, que tengo el pelo pobre!"),
                new QuoteModel(20, "Otra crisis solucionada por la administración Recio, ¡Qué bueno soy y qué culito tengo!"),
                new QuoteModel(21, "No hay crisis grandes, sino presidentes pequeños."),
                new QuoteModel(22, "¡Coque! ¡Péinate esa cresta!"),
                new QuoteModel(23, "¡Viva el rey y viva España!"),
                new QuoteModel(24, "¡Tres juntas de suspensión!"),
                new QuoteModel(25, "Yo hice la mili en Ceuta. ¡No se me colaba ni uno!"),
                new QuoteModel(26, "Mi hermana es como yo... pero con pelo."),
                new QuoteModel(27, "¡Hostia terrible!"),
                new QuoteModel(28, "¡Pues te confiscó el felpudo!"),
                new QuoteModel(29, "¿Le has quitado el móvil a tu presidente? ¡Despedido!"),
                new QuoteModel(30, "¡Os voy a subir las cuotas!"),
                new QuoteModel(31, "Yo no soy racista, soy ordenado. Si Dios nos separó en continentes, por algo sería."),
                new QuoteModel(32, "¡Morirá entre terribles sufrimientos!"),
                new QuoteModel(33, "¡Hostia monumental¡"),
                new QuoteModel(34, "Los pelochochos; los muñecos telefonistas de la tele."),
                new QuoteModel(35, "¡Demanda judicial!"),
                new QuoteModel(36, "Si incluso a Zapatero se le ha perdido el respeto, ¡le llaman ZP, como si fuese un rapero!"),
                new QuoteModel(37, "¡Protege a tu presidente!"),
                new QuoteModel(38, "Pero como voy a la cárcel, que soy un caramelito."),
                new QuoteModel(39, "Qué gestión."),
                new QuoteModel(40, "Coque Otro mes que no cobras."),
                new QuoteModel(41, "Normal que haya paro...Si cada inmigrante se coge dos trabajos...¡Avariciosos!"),
                new QuoteModel(42, "¡Fresquísimo todo!"),
                new QuoteModel(43, "¡Comunista!"),
                new QuoteModel(44, "Enrique, cuando consigas tu primera dama serás presidente, ¡Si yo lo quiero dejar!"),
                new QuoteModel(45, "Enrique, esa no me gusta para ti."),
                new QuoteModel(46, "Hasta que no saquen los tanques..."),
                new QuoteModel(47, "¡Golpe de Estado!"),
                new QuoteModel(48, "Todo el mundo en pie, que va a empezar la junta."),
                new QuoteModel(49, "Es un plan excelente digno de una mente superior."),
                new QuoteModel(50, "Gracias a mi mente prilidegiada que echa humo..."),
                new QuoteModel(51, "Me atacaron 5 encapuchados con sprays pica-pica, pero con mi paraguas, que en mis manos se convierte en una arma letal, los contrarresté."),
                new QuoteModel(52, "Me intentó persuadir con sus métodos de psicóloga pero me contuve."),
                new QuoteModel(53, "Mariscos Recio patrocina este gol."),
                new QuoteModel(54, "¡Cállate, limpiacacas!"),
                new QuoteModel(55, "¿Portazo a tu presidente? ¡Pues te confiscó el felpudo!"),
                new QuoteModel(56, "!A ver, control de alcoholemia, sople aquí!"),
                new QuoteModel(57, "¡Pues te orino el felpudo!"),
                new QuoteModel(58, "Que todos los genes del niño sean míos, menos el pelo que puede ser de ella...es que el mío es un poco pobre."),
                new QuoteModel(59, "¡¿Pero cómo voy a trabajar en una pescadería, si soy Antonio Recio, mayorista, y no limpio pescado!?."),
                new QuoteModel(60, "Estos son mis dominios y los pienso recuperar."),
                new QuoteModel(61, "Enrique, eres mi delfín hasta el fin."),
                new QuoteModel(62, "Yo en Dios no confío, si hasta crucificó a su hijo."),
                new QuoteModel(63, "El presidente vela por vosotros."),
                new QuoteModel(64, "Ya verás que de aquí a 10 años vamos todos con taparrabos."),
                new QuoteModel(65, "Los huesos de ellos sueldan más rápido ¿No ves que se tienen que defender de cocodrilos?"),
                new QuoteModel(66, "Arrodíllate ante la espada de Hernán Cortés como tus antepasados indígenas."),
                new QuoteModel(67, "Enrique, cómo te gusta el poder."),
                new QuoteModel(68, "Un llavero de Mariscos Recio, tú esto lo enseñas y ya entras en todas partes."),
                new QuoteModel(69, "A mí no me pueden violar porque tengo un mecanismo de defensa ancestral en las paredes del glúteo."),
                new QuoteModel(70, "Mariscos Recio, el mar al mejor recio"),
                new QuoteModel(71, "Coque, un imperio no se puede gobernar con el estómago vacío."),
                new QuoteModel(72, "Enrique te indulto porque eres mi amigo."),
                new QuoteModel(73, "Cómo desgasta el poder."),
                new QuoteModel(74, "Pues te adelanto con mi sprint de mayorista."),
                new QuoteModel(75, "Despedido."),
                new QuoteModel(76, "Como oferta de apertura, unos precios de locura."),
                new QuoteModel(77, "¿Pero que le has hecho a mi salón? Parece la cabaña de Atahualpa Yupanqui."),
                new QuoteModel(78, "Esto con Antonio Recio no pasaba."),
                new QuoteModel(79, "¡Lo impugno!"),
                new QuoteModel(80, "¡Impugno que no se pueda impugnar!"),
                new QuoteModel(81, "Su pescadería divina a la vuelta de la esquina."),
                new QuoteModel(82, "Te voy a quitar la etiqueta, no vayas a pitar en la puerta."),
                new QuoteModel(83, "Parrales, no mires atrás, vuelve a tu selva natal."),
                new QuoteModel(84, "Ea ea ea, me cago en todo lo que se menea."),
                new QuoteModel(85, "En el Imperio español nunca se ponía el Sol... ¡Luego llegaron los socialistas y se jodió todo!"),
                new QuoteModel(86, "Serpiente pitón, cumple con tu misión."),
                new QuoteModel(87, "Esta presidenta nos ha devuelto al Paleolítico, ya ni podemos hacer popó en nuestras casas, lo tenemos que hacer en el descampado.  ¡Esto con Antonio Recio no pasaba!"),
                new QuoteModel(88, "¿Cómo que mi pescadería imperial huele a podrido? Es sólo olor a mar."),
                new QuoteModel(89, "Espera, Parrales, que salto la valla, que has flipao, yo hice la mili en Ceuta."),
                new QuoteModel(90, "Parrales, estás muy civilizado, seguro que en tu selva natal no aguantas vivo ni un minuto."),
                new QuoteModel(91, "Creí que no podías caer más bajo, pero en el sótano de tu fracaso siempre hay una planta más."),
                new QuoteModel(92, "Darwin era un comunista resentido. ¿Cómo voy a venir yo de un mono?"),
                new QuoteModel(93, "Oh, una indígena inocente. Soy Hernán Cortés, siervo del imperio español, donde no se pone el Sol."),
                new QuoteModel(94, "Manolita, a estos colchones no estáis acostumbrados ¿eh?, claro, durmiendo en árboles."),
                new QuoteModel(95, "Como signo de una amistad sincera te regalo 1 kilo de gambas... cómetelas hoy, que empiezan a oler raro."),
                new QuoteModel(96, "Parrales, te prohíbo que te cases con Mari Carmen, ¿Te das cuenta que se puede mancillar el linaje de mi especie?"),
                new QuoteModel(97, "¡Yo levanté un imperio de la nada!"),
                new QuoteModel(98, "Si yo me hubiera derrumbado en la primera crisis de la gripe del centollo ahora no sería lo que soy."),
                new QuoteModel(99, "Enrique, no te preocupes, que cuando el PP gane las elecciones perseguirán a las bolleras y a los invertidos para hacer experimentos con ellos."),
                new QuoteModel(100, "La pureza de la especie ibérica esta en peligro y no te importa. ¡¡¡Enrique, rojo resentido!!!."),
                new QuoteModel(101, "¿Quieres formar parte de mi harén?"),
                new QuoteModel(102, "Ay, que alegría, ya sentía yo los genes del Cid en mis venas."),
                new QuoteModel(103, "Vamos a comernos un perrito caliente, que ya no tengo descendientes de Alí Baba."),
                new QuoteModel(104, "Si tiene una cena elegante, llévese un bogavante. Si tiene una cena muy fina, llévese una lubina. Si tiene una cena de gala, llévese una cigala."),
                new QuoteModel(105, "Si tiene una cena elegante, llévese un bogavante."),
                new QuoteModel(106, "Si tiene una cena muy fina, llévese una lubina."),
                new QuoteModel(107, "Si tiene una cena de gala, llévese una cigala."),
                new QuoteModel(108, "Como oferta de apertura, unos precios de locura."),
                new QuoteModel(109, "Y por aquí no pasa ni Dios; este barrio esta muerto."),
                new QuoteModel(110, "Parados sin futuro, estáis de suerte. Mariscos Recio, empresa líder del congelado, amplía su plantilla y ofrece un puesto de trabajo."),
                new QuoteModel(111, "Emiliano Parrales, mayorista de café, no recojo grano"),
                new QuoteModel(112, "He probado eso de dejar la mente en blanco en la ducha, y casi me mato, pero me caía una agüita calentita, me siento mucho más relajado."),
                new QuoteModel(113, "Antonio Recio al aparato."),
                new QuoteModel(114, "Conrado, mi abogado."),
                new QuoteModel(115, "Detened vuestros destornilladores, chapuzas a sueldo"),
                new QuoteModel(116, "Pero si está clarísimo, ¡que el muerto está moroso y el vivo muerto!"),
                new QuoteModel(117, "Morirás entre terrible sufrimiento."),
                new QuoteModel(118, "¡Me minas la moral!"),
                new QuoteModel(119, "Antonio Recio, mayorista, no limpio pescado; me he quedado sin tarjetas."),
                new QuoteModel(120, "¡Mariscos Recio, el mar al mejor precio! ¡Si tiene una cena elegante, llévese un bogavante; si tiene una cena de gala, llévese una cigala; si tiene una cena muy fina, llévese una lubina!"),
                new QuoteModel(121, "O me atiendes, o te denuncio al colegio de odontólogos."),
                new QuoteModel(122, "¡Cómo que una plantita, si eso parecía Parque Jurásico; faltaba el tío con la metralleta vigilando la plantación!"),
                new QuoteModel(123, "¡El 'Señor' lo ha fulminado con su rayo celestial!"),
                new QuoteModel(124, "¡Atrás, nos atacan! ¡A mí la Guardia de Montepinar!"),
                new QuoteModel(125, "¡La limpia que voy a hacer en este país cuando sea presidente!"),
                new QuoteModel(126, "¡Violeta, Stop! ¡¿Le habéis dado el Phoskito?!"),
                new QuoteModel(127, "Al sofá va el bicho que es la que no paga."),
                new QuoteModel(128, "Que estamos en rojos, melón!"),
                new QuoteModel(129, "¡Ay, qué poca iniciativa...!"),
                new QuoteModel(130, "Aprobado por mayoría, ¡nos vamos al casino!"),
                new QuoteModel(131, "Buenas tardes. Viva el rey y viva España. Viva el king y viva Spain. Casino closing por reforming. The Spanish governament preocupating por de turists, inviting you a inauguration del Gran Casino de Montepinar."),
                new QuoteModel(132, "Lees más rápido en chino que en español."),
                new QuoteModel(133, "¿Cómo que quiénes somos? ¡La autoridad! ¡Papeles!"),
                new QuoteModel(134, "Tranquilidad, don't worry everybody. Pueden fuming, pueden drinking, Ay... hala... ya me los he ganado. ¡Qué importante es saber idiomas!"),
                new QuoteModel(135, "¡Era una partidilla entre amigos, como en el Monopoly, las fichas eran de plástico, aquí no tenemos fondos!"),
                new QuoteModel(136, "¡Cuando yo sea presidente los voy a echar a todos! ¡Despedido! Otro triunfo de la administración Recio. ¡Qué bueno soy y qué culito tengo!")
            };

            return theQuotes;
        }
    }
}
